#pragma once

// Auto-generated by PlatformIO extra_script: generate_webfiles.py
#define ESPWEBUTILS_LIBRARY_VERSION "0.6.0"
#define ESPWEBUTILS_WEBFILES_HASH "a85c9edc82f3f6c01b843f681edd3f52cc2cf0ebce1b4c002c7592880a9f2eea"
#define WEBFILES_HASH ESPWEBUTILS_WEBFILES_HASH
