#pragma once

// Auto-generated by PlatformIO extra_script: generate_webfiles.py
#define ESPWEBUTILS_LIBRARY_VERSION "0.5.0"
#define ESPWEBUTILS_WEBFILES_HASH "c3d3abb02ed649e6bf775c48b785f25555051edccc18e00bf9230025b518e65f"
#define WEBFILES_HASH ESPWEBUTILS_WEBFILES_HASH
