#pragma once

// Auto-generated by PlatformIO extra_script: generate_webfiles.py
#define ESPWEBUTILS_LIBRARY_VERSION "0.6.8"
#define ESPWEBUTILS_WEBFILES_HASH "a9142d2868004beb26dce08e8a957d32fd08429b17781a0ea21977adb40e809f"
#define WEBFILES_HASH ESPWEBUTILS_WEBFILES_HASH
